export enum ExceptionCode {
  EXPIRED_JWT = 'EXPIRED_JWT',
  INVALID_JWT = 'INVALID_JWT',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  WRONG_PASSWORD = 'WRONG_PASSWORD',
  USER_MISSING = 'USER_MISSING',
  USER_NOT_AUTHORIZED = 'USER_NOT_AUTHORIZED',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
}
